# Generated by Django 5.1.7 on 2025-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_title',
            field=models.TextField(default='No title', max_length=500),
        ),
        migrations.AddField(
            model_name='challenge',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_photo',
            field=models.ImageField(blank=True, null=True, upload_to='challenges/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='finish_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(default='default1.png', max_length=15),
        ),
    ]
