# Generated by Django 5.1.7 on 2025-04-16 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge_main', '0002_challenge_challenge_title_challenge_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='likes',
        ),
        migrations.CreateModel(
            name='ChallengeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forge_main.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
