# Generated by Django 5.1.7 on 2025-05-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge_main', '0004_challengeparticipationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
    ]
